CREATE TABLE `registration` (
  `userId` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `unique_id` int(20) unsigned DEFAULT NULL,
  `firstName` varchar(50) NOT NULL DEFAULT '',
  `lastName` varchar(50) NOT NULL DEFAULT '',
  `dateOfBirth` date DEFAULT NULL,
  `password` blob,
  `email` varchar(255) NOT NULL DEFAULT '',
  `address` varchar(255) NOT NULL DEFAULT '',
  `address1` varchar(255) DEFAULT NULL,
  `State` varchar(20) NOT NULL DEFAULT '0',
  `countryId` int(11) DEFAULT NULL,
  `zipCode` varchar(50) NOT NULL DEFAULT '',
  `city` varchar(50) NOT NULL DEFAULT '',
  `phone` varchar(50) NOT NULL DEFAULT '0',
  `mobile` varchar(50) NOT NULL DEFAULT '',
  `name` smallint(5) unsigned NOT NULL DEFAULT '0',
  `hintAnswer` varchar(50) NOT NULL DEFAULT '',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `postedDate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `preApproved` enum('Y','N') DEFAULT 'N',
  `preApprovalAmount` varchar(50) DEFAULT NULL,
  `bidderNumber` varchar(20) DEFAULT NULL,
  `username` varchar(100) NOT NULL,
  `seller_bidder` int(11) NOT NULL,
  `suspend` int(11) NOT NULL,
  `vip_status` tinyint(4) NOT NULL,
  `countyId` int(11) DEFAULT NULL,
  `locationflag` enum('us','uk') DEFAULT 'us',
  `autoseller_group_id` int(11) NOT NULL,
  `companyName` varchar(255) DEFAULT NULL,
  `title` varchar(30) NOT NULL,
  `heardAboutUs` varchar(100) DEFAULT NULL,
  `DRENumber` varchar(20) DEFAULT NULL,
  `officeNumber` varchar(20) DEFAULT NULL,
  `brokerFirmName` varchar(100) DEFAULT NULL,
  `brokerEmail` varchar(100) DEFAULT NULL,
  `areaOfSpeciality` varchar(100) DEFAULT NULL,
  `JoinDate` datetime DEFAULT NULL,
  `bio` text,
  `documentSubscription` enum('Y','N') NOT NULL DEFAULT 'Y',
  `EmailNewsletterPrefer` enum('Yes','No') NOT NULL DEFAULT 'Yes',
  `RegularMailPrefer` enum('Yes','No') NOT NULL DEFAULT 'Yes',
  `TelephonePrefer` enum('Yes','No') NOT NULL DEFAULT 'Yes',
  `MobilePrefer` enum('Yes','No') NOT NULL DEFAULT 'Yes',
  `SMSPrefer` enum('Yes','No') NOT NULL DEFAULT 'Yes',
  `institutionDepositORD` enum('Y','N') DEFAULT 'N',
  `institutionVIP` enum('Y','N') DEFAULT NULL,
  `VIPSellerAllowed` varchar(150) DEFAULT NULL,
  `rememberMe` varchar(100) DEFAULT NULL,
  `IsSupportUser` tinyint(1) NOT NULL DEFAULT '0',
  `promocode` varchar(255) NOT NULL,
  `CNFRMD_DATE` datetime DEFAULT NULL,
  `Signup_Source` varchar(12) DEFAULT NULL,
  `fpwd_random_str` varchar(100) DEFAULT NULL,
  `fpwd_exp_time` timestamp NULL DEFAULT NULL,
  `contract_specialist_id` int(11) DEFAULT NULL COMMENT '0 for Unassigned',
  `prefix` varchar(35) DEFAULT NULL,
  `email_preference` enum('de','en') DEFAULT 'en',
  `aml_status` varchar(20) DEFAULT 'Pending',
  `aml_expired_date` date DEFAULT NULL,
  `entity_type` varchar(20) DEFAULT NULL,
  `approve_from` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0=> approve from mail, 1=> approve from mlh',
  `updatedBy` int(11) NOT NULL DEFAULT '0',
  `updatedDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `offerBuyer` tinyint(1) DEFAULT NULL,
  `isFirstLogin` tinyint(1) unsigned NOT NULL,
  `createdBy` int(11) NOT NULL DEFAULT '0',
  `createdDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`),
  KEY `firstname` (`firstName`),
  KEY `Lastname` (`lastName`),
  KEY `Status` (`status`),
  KEY `seller_bidder` (`seller_bidder`),
  KEY `email` (`email`),
  KEY `username` (`username`),
  KEY `unique_id` (`unique_id`),
  KEY `IsSupportUser` (`IsSupportUser`),
  KEY `registration_Idx_updatedDate` (`updatedDate`),
  KEY `reg_fpwd_random_str_indx` (`fpwd_random_str`)
) ENGINE=InnoDB ;
