CREATE TABLE `users` (
  `userID` int(10) NOT NULL AUTO_INCREMENT,
  `userType` varchar(255) NOT NULL,
  `brokerEmailAddress` varchar(255) DEFAULT NULL,
  `firstName` varchar(30) NOT NULL DEFAULT '',
  `middleInitial` varchar(20) NOT NULL DEFAULT '',
  `lastName` varchar(30) NOT NULL DEFAULT '',
  `address` varchar(100) NOT NULL DEFAULT '',
  `address2` varchar(100) NOT NULL DEFAULT '',
  `adr1_type` varchar(50) NOT NULL,
  `adr2_type` varchar(50) NOT NULL,
  `city` varchar(30) NOT NULL DEFAULT '',
  `searchStateID` int(10) NOT NULL DEFAULT '0',
  `zip` int(10) NOT NULL DEFAULT '0',
  `region` int(11) NOT NULL DEFAULT '0',
  `countyID` int(10) NOT NULL DEFAULT '0',
  `phone` varchar(50) NOT NULL DEFAULT '0',
  `workPhone` varchar(20) NOT NULL DEFAULT '',
  `mobilePhone` varchar(20) NOT NULL DEFAULT '',
  `alternateContact` varchar(50) NOT NULL,
  `alternatePhone` varchar(20) NOT NULL,
  `fax` varchar(20) NOT NULL DEFAULT '',
  `workPhoneExt` varchar(10) NOT NULL DEFAULT '',
  `phoneExt` varchar(10) NOT NULL DEFAULT '',
  `mobilePhoneExt` varchar(10) NOT NULL DEFAULT '',
  `faxExt` varchar(10) NOT NULL DEFAULT '',
  `company` varchar(50) NOT NULL DEFAULT '',
  `department` varchar(20) NOT NULL DEFAULT '',
  `echelon` char(2) NOT NULL DEFAULT '',
  `notary` varchar(10) NOT NULL DEFAULT '',
  `username` varchar(100) NOT NULL,
  `alternateEmail` varchar(50) NOT NULL DEFAULT '',
  `password` blob NOT NULL,
  `status` enum('Y','N') NOT NULL DEFAULT 'N',
  `newEntry` tinyint(1) NOT NULL DEFAULT '0',
  `preferenceSR` varchar(255) NOT NULL DEFAULT '',
  `preferenceTR` varchar(255) NOT NULL DEFAULT '',
  `preferenceTS` varchar(255) NOT NULL DEFAULT '',
  `preferenceNRPI` varchar(255) NOT NULL DEFAULT '',
  `question` tinyint(2) NOT NULL DEFAULT '0',
  `answer` varchar(255) NOT NULL DEFAULT '',
  `roleID` varchar(50) NOT NULL DEFAULT '0',
  `moderated` tinyint(1) NOT NULL DEFAULT '0',
  `statesAccess` varchar(100) NOT NULL DEFAULT '',
  `NRPIfields` tinyint(1) NOT NULL DEFAULT '0',
  `mediaCompany` int(11) NOT NULL,
  `lisenceNumber` varchar(20) NOT NULL,
  `agentBrokerState` varchar(50) DEFAULT NULL,
  `lisenceExpDate` date NOT NULL,
  `requestDate` date NOT NULL,
  `encryptEmail` varchar(100) NOT NULL,
  `sessId` varchar(100) NOT NULL,
  `mlhUserPhoto` varchar(150) DEFAULT NULL,
  `mlhUserPhoto_thumb` varchar(150) DEFAULT NULL,
  `agentPageName` varchar(100) DEFAULT NULL,
  `areaOfSpecialization` varchar(255) DEFAULT NULL,
  `personalMess` text,
  `licenseNumber` varchar(100) DEFAULT NULL,
  `is_closing_user` enum('1','0') NOT NULL DEFAULT '0',
  `access_lender` varchar(255) DEFAULT NULL,
  `access_CC` varchar(255) DEFAULT NULL,
  `access_DCC` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `rememberMe` varchar(100) NOT NULL,
  `contractSpecialist` tinyint(1) NOT NULL DEFAULT '0',
  `validateContractReceived` tinyint(1) NOT NULL DEFAULT '0',
  `IsVIPClientRepresentative` tinyint(1) DEFAULT '0',
  `createdBy` int(11) NOT NULL DEFAULT '0',
  `createdDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedBy` int(11) NOT NULL DEFAULT '0',
  `updatedDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`userID`),
  KEY `firstName` (`firstName`),
  KEY `lastName` (`lastName`),
  KEY `city` (`city`),
  KEY `username` (`username`),
  KEY `status` (`status`),
  KEY `roleID` (`roleID`),
  KEY `is_closing_user` (`is_closing_user`),
  KEY `Users_idx_Remem` (`rememberMe`),
  KEY `users_Idx_updatedDate` (`updatedDate`),
  KEY `users_Idx_contractSpecialist_status` (`contractSpecialist`,`status`)
) ENGINE=InnoDB ;
