CREATE TABLE `bid_live` (
  `bidID` int(255) NOT NULL AUTO_INCREMENT,
  `userId` int(11) NOT NULL DEFAULT '0',
  `auctionID` int(11) NOT NULL DEFAULT '0',
  `propertyId` int(11) NOT NULL DEFAULT '0',
  `bidDateTime` varchar(255) DEFAULT NULL,
  `bidAmount` bigint(20) DEFAULT NULL,
  `ip` varchar(100) DEFAULT NULL,
  `type` enum('normal','proxy') NOT NULL,
  `flag` int(11) NOT NULL DEFAULT '1',
  `auto_seller_bidding` int(11) NOT NULL DEFAULT '0',
  `last_altered` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedBy` int(11) DEFAULT '0',
  `createdDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` int(11) DEFAULT '0',
  `oAuthId` int(10) DEFAULT NULL,
  `sourceId` int(10) DEFAULT NULL,
  `pageName` varchar(15) DEFAULT NULL,
  `sessionId` varchar(50) DEFAULT NULL,
  `cookieId` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`bidID`),
  UNIQUE KEY `bidlive_multiidx2` (`propertyId`,`bidAmount`,`flag`),
  KEY `flag` (`flag`),
  KEY `userid` (`userId`),
  KEY `bidlive_multiidx1` (`auctionID`,`propertyId`,`flag`,`userId`,`type`,`bidAmount`,`bidDateTime`),
  KEY `bid_live_Idx_last_altered` (`last_altered`)
) ENGINE=InnoDB ;
