CREATE TABLE `property` (
  `propertyId` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `globalPropID` int(11) unsigned NOT NULL,
  `auctionID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `venueCode` varchar(10) NOT NULL DEFAULT '0',
  `lotPackage` varchar(10) DEFAULT NULL,
  `redcOldID` varchar(10) NOT NULL,
  `venueId` smallint(5) unsigned NOT NULL DEFAULT '0',
  `loanNo` varchar(50) NOT NULL DEFAULT '',
  `MLSID` varchar(50) DEFAULT NULL,
  `propertyAddress` tinytext NOT NULL,
  `propertyAddressSearch` varchar(255) DEFAULT NULL,
  `propertyName` text,
  `propertyCity` varchar(60) NOT NULL,
  `propertyCounty` varchar(50) NOT NULL DEFAULT '',
  `propertyState` varchar(50) NOT NULL DEFAULT '',
  `propertyZip` varchar(6) DEFAULT NULL,
  `propertyType` varchar(50) NOT NULL DEFAULT '',
  `propertyDescription` tinytext NOT NULL,
  `propertyOccupancyStatus` text,
  `auctionDate` varchar(50) DEFAULT NULL,
  `openHouse1` varchar(50) NOT NULL DEFAULT '',
  `openHouse2` varchar(50) NOT NULL DEFAULT '',
  `openHouse3` varchar(50) NOT NULL DEFAULT '',
  `openHouseConfirmation1` enum('Appt Only','No','Yes','TBD') DEFAULT NULL,
  `openHouseConfirmation2` enum('Appt Only','No','Yes','TBD') DEFAULT NULL,
  `openHouseConfirmation3` enum('Appt Only','No','Yes','TBD') DEFAULT NULL,
  `reoCurrentListPrice` float(20,2) DEFAULT NULL,
  `highestEverListPrice` decimal(15,2) DEFAULT NULL COMMENT 'NULL or Numeric',
  `grcAM` varchar(200) DEFAULT '',
  `grcAMPhone` varchar(50) DEFAULT '',
  `grcAMEmail` varchar(200) DEFAULT '',
  `brokerCompany` varchar(200) DEFAULT NULL,
  `brokerLogo` varchar(100) NOT NULL,
  `brokerAddress` varchar(150) DEFAULT NULL,
  `brokerCity` varchar(100) DEFAULT NULL,
  `brokerState` varchar(30) DEFAULT NULL,
  `brokerZip` varchar(10) DEFAULT NULL,
  `broker_license_number` varchar(45) DEFAULT NULL,
  `currentBrokerAgent` varchar(250) DEFAULT '',
  `brokerPhone` varchar(50) DEFAULT '',
  `brokerEmail` varchar(250) DEFAULT '',
  `totalRoomCount` tinyint(2) DEFAULT NULL COMMENT '1-50 or NULL',
  `homeSquareFootage` smallint(6) DEFAULT NULL COMMENT '200 to 20000 or NULL',
  `bedrooms` tinyint(2) DEFAULT NULL COMMENT '1-50 or NULL',
  `baths` float DEFAULT NULL COMMENT '1-10 or NULL',
  `lotSize` float DEFAULT NULL COMMENT '.01-200 or NULL',
  `yearBuilt` smallint(4) DEFAULT NULL COMMENT '1700-Today[Year] or NULL',
  `legalDescription` text,
  `HOAName` varchar(100) DEFAULT NULL,
  `HOAPhone` varchar(20) DEFAULT NULL,
  `hoaDue` float(7,2) DEFAULT NULL COMMENT '1-2000 or NULL',
  `photoCount` smallint(6) NOT NULL,
  `status` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `isDel` enum('0','1') NOT NULL DEFAULT '0',
  `mlsComment` longtext,
  `principalBalance` float(9,2) DEFAULT NULL,
  `propertyOrder` varchar(100) NOT NULL DEFAULT '0',
  `newPropOrder` varchar(10) NOT NULL,
  `startingBid` decimal(15,2) DEFAULT NULL COMMENT 'NULL or Numeric',
  `previouslyValuedTo` double(15,2) DEFAULT NULL,
  `researchedValue` float(10,2) DEFAULT NULL,
  `FNMAApproved` varchar(10) DEFAULT NULL,
  `financingAvailable` varchar(50) DEFAULT '',
  `sellerFinance` varchar(10) DEFAULT NULL,
  `FHAAvailable` varchar(10) DEFAULT NULL,
  `financingType` varchar(50) NOT NULL DEFAULT '',
  `poolNumber` varchar(15) NOT NULL,
  `outsourcerID` varchar(255) NOT NULL,
  `outSourcerContactName` varchar(100) DEFAULT NULL,
  `outSourcerContactEmail` varchar(100) DEFAULT NULL,
  `outSourcerContactPhone` varchar(20) DEFAULT NULL,
  `lockBoxCode` varchar(50) DEFAULT '',
  `completedDate` varchar(50) DEFAULT '',
  `estRepairs` varchar(50) NOT NULL DEFAULT '',
  `condition` varchar(50) DEFAULT '',
  `agent90AsIs` decimal(15,2) DEFAULT NULL COMMENT 'Null or Numeric',
  `RMVDate` date DEFAULT NULL,
  `mV90AsIs` varchar(50) NOT NULL DEFAULT '',
  `sL90AsIs` varchar(50) NOT NULL DEFAULT '',
  `mV90Repair` varchar(50) NOT NULL DEFAULT '',
  `sL90Repair` varchar(50) NOT NULL DEFAULT '',
  `aprAsls` decimal(15,2) DEFAULT NULL COMMENT 'Null or Numeric',
  `aprRepair` float(9,2) DEFAULT NULL COMMENT '1-3000000 or NULL',
  `RMVComments` text,
  `grcAsls` varchar(100) NOT NULL DEFAULT '',
  `prevListPrice` float(15,2) DEFAULT NULL COMMENT 'more then 1 or NULL',
  `prevSalePrice` float(9,2) DEFAULT NULL COMMENT '1-3000000 or NULL',
  `prevSaleDate` varchar(50) DEFAULT '',
  `taxAssessedValue` float(9,2) DEFAULT NULL COMMENT '1-3000000 or NULL',
  `noListings` varchar(50) NOT NULL DEFAULT '',
  `avgPrice_1` varchar(50) NOT NULL DEFAULT '',
  `low_1` varchar(50) NOT NULL DEFAULT '',
  `high_1` varchar(50) NOT NULL DEFAULT '',
  `noDirectComp` varchar(50) NOT NULL DEFAULT '',
  `avgPrice_2` varchar(50) NOT NULL DEFAULT '',
  `low_2` varchar(50) NOT NULL DEFAULT '',
  `high_2` varchar(50) NOT NULL DEFAULT '',
  `avgDOM` smallint(6) DEFAULT NULL COMMENT '1-365 or NULL',
  `SpecialAccess` varchar(255) NOT NULL DEFAULT '',
  `StatusCSV` enum('Auction','Sold Presale','Removed','Eviction','Closed/Sold','Under Contract','Postponed','Cancelled') DEFAULT NULL,
  `presaleSoldDate` date DEFAULT NULL,
  `Directions` varchar(255) DEFAULT '',
  `UpdatedAddress` text,
  `postAuctionSales` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `PAMP` varchar(50) NOT NULL DEFAULT '',
  `soldStatus` varchar(10) NOT NULL DEFAULT '',
  `winningBid` double(15,2) DEFAULT NULL,
  `ReoHighBid` double DEFAULT NULL,
  `pkgWinningBid` float NOT NULL,
  `OwnerOccupiedSellerIncentive` float(9,2) DEFAULT NULL,
  `closingCost` float(9,2) DEFAULT NULL,
  `applianceCost` float(9,2) DEFAULT NULL,
  `visitDays` mediumint(8) unsigned NOT NULL DEFAULT '1',
  `visits` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `uniqueVisits` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `perDayVisits` smallint(5) unsigned NOT NULL DEFAULT '0',
  `perDayUniqueVisits` smallint(5) unsigned NOT NULL DEFAULT '0',
  `buyerLastName` varchar(50) NOT NULL DEFAULT '',
  `seller` text,
  `servicer` varchar(5000) DEFAULT NULL,
  `loanType` varchar(100) NOT NULL DEFAULT '',
  `loanApprovalStatus` varchar(100) NOT NULL DEFAULT '',
  `lenderReserve` varchar(50) NOT NULL DEFAULT '',
  `updatedReserve` varchar(50) NOT NULL DEFAULT '',
  `auctionSellerReserve` decimal(15,2) DEFAULT NULL,
  `agentValue` varchar(50) NOT NULL DEFAULT '',
  `grcValue` varchar(50) NOT NULL DEFAULT '',
  `cancelReason` text NOT NULL,
  `cancelDate` varchar(50) NOT NULL DEFAULT '',
  `reloadReason` text NOT NULL,
  `reloadDate` varchar(50) NOT NULL DEFAULT '',
  `daysSinceReload` int(10) NOT NULL DEFAULT '0',
  `reloadNotes` text NOT NULL,
  `statusUpdatedReserve` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `winningBidFlag` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `soldStatusFlag` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `slideShowOrder` smallint(3) unsigned NOT NULL,
  `sellerConfirmation` tinyint(1) unsigned NOT NULL,
  `percentDownPayment` smallint(3) unsigned NOT NULL,
  `downPaymentAtPurchaseTime` varchar(50) NOT NULL,
  `calculatedEarnestMoney` float(9,2) DEFAULT NULL,
  `pkgEarnestMoney` float NOT NULL,
  `earnMoneyUnit` enum('prop','pkg') NOT NULL DEFAULT 'prop',
  `buyerPremiumPerc` float(8,2) NOT NULL,
  `buyersPremiumAmount` float(10,2) NOT NULL,
  `auctionDayStatus` smallint(3) unsigned NOT NULL DEFAULT '2',
  `statusLastUpdated` datetime NOT NULL,
  `sellerConfirmLastEditedBy` mediumint(8) unsigned NOT NULL,
  `winBidLastEditedBy` mediumint(8) unsigned NOT NULL,
  `lender` mediumint(8) unsigned NOT NULL,
  `reserve` varchar(50) NOT NULL,
  `reconciled` enum('Yes','No') NOT NULL DEFAULT 'No',
  `reconciled_lastUpdatedBy` int(11) unsigned NOT NULL,
  `isResultEmail` enum('0','1') NOT NULL DEFAULT '0',
  `redcid` varchar(255) NOT NULL,
  `subjectToStatus` enum('a','r','p','c','o','co') NOT NULL DEFAULT 'p',
  `subjToStatusUpdatedOn` date NOT NULL,
  `isOnlineBidder` enum('Y','N') NOT NULL DEFAULT 'N',
  `remarks` longtext NOT NULL,
  `cashDeal` enum('0','1') NOT NULL DEFAULT '0',
  `footTraffic` varchar(100) DEFAULT NULL COMMENT '1-5000 or NULL',
  `cmacceptance` enum('Y','N') NOT NULL DEFAULT 'N',
  `cmacceptanceChangedBy` int(11) unsigned NOT NULL,
  `cmacceptanceChangedOn` date NOT NULL,
  `closing_company` varchar(200) DEFAULT NULL,
  `closingCompanyContact` varchar(100) DEFAULT NULL,
  `closingCompanyPhone` varchar(20) DEFAULT NULL,
  `closingCompanyEmail` varchar(100) DEFAULT NULL,
  `local_closing_company` varchar(200) DEFAULT NULL,
  `escrow_officer` varchar(100) DEFAULT NULL,
  `escrow_officer_phone` varchar(20) DEFAULT NULL,
  `escrow_officer_email` varchar(100) DEFAULT NULL,
  `LCC_RAD_ID` varchar(50) NOT NULL,
  `finance_notes` longtext,
  `subjectToReserve` varchar(20) DEFAULT NULL COMMENT '1-2000000 or SUBJECT TO or SUBJECT TO MI or  NULL',
  `propertyWatchGrade` varchar(50) DEFAULT NULL,
  `propertyConditionsGrade` varchar(50) DEFAULT NULL,
  `agentPerformanceGrade` varchar(50) DEFAULT NULL,
  `PreAuctionOpsGrade` varchar(50) DEFAULT NULL,
  `totalGradeReview` varchar(50) DEFAULT NULL,
  `finance_web_comments` text,
  `bpoCompletedDate` date DEFAULT NULL COMMENT '2007-Current Year or NULL',
  `assetPriorListPrice` float(10,2) DEFAULT NULL,
  `assetPriorListDate` date DEFAULT NULL,
  `auctioneer` smallint(4) NOT NULL,
  `subauctioneer` int(11) DEFAULT NULL,
  `acceptableOffer` float(9,2) DEFAULT NULL,
  `bidStartDT` datetime NOT NULL,
  `bidEndDT` datetime NOT NULL,
  `flag_online_bid` int(11) NOT NULL,
  `biddingStatus` tinyint(4) NOT NULL,
  `numPropOrder` int(11) NOT NULL,
  `alphaPropOrder` varchar(2) NOT NULL,
  `managed_by` enum('REDC','GRC') DEFAULT NULL,
  `rmv_vendor` enum('REDC','GRC','BMG','OCWEN','CITI') DEFAULT NULL,
  `foreclosureAttorney` varchar(200) DEFAULT NULL,
  `foreclosureAttorneyPhone` varchar(20) DEFAULT NULL,
  `foreclosureAttorneyEmail` varchar(100) DEFAULT NULL,
  `titleUnderwriter` varchar(200) DEFAULT NULL,
  `titleOrderDate` date DEFAULT NULL,
  `autosellerbidover` int(11) NOT NULL DEFAULT '0',
  `buyerPremium` double(15,2) DEFAULT NULL,
  `last_altered` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `reserveSubjectToValue` double(15,2) DEFAULT NULL,
  `reserveSubjectToPerc` float(8,4) NOT NULL,
  `preSaleStatus` enum('Sold','Active') DEFAULT NULL,
  `preferredLender` varchar(5) DEFAULT NULL,
  `presaleReserve` float DEFAULT NULL,
  `onlineST` int(11) NOT NULL,
  `onlineStChanged` enum('0','1') NOT NULL DEFAULT '0',
  `last_push_closing_date` datetime DEFAULT NULL,
  `push_closing_cnt` int(11) DEFAULT NULL,
  `sellerBpoValue` decimal(15,2) DEFAULT NULL COMMENT 'NULL or Numeric',
  `sellerBpoDate` date DEFAULT NULL,
  `acceptedOfferDate` date DEFAULT NULL,
  `lastOfferDate` date DEFAULT NULL,
  `lastOfferAmount` float(9,2) DEFAULT NULL,
  `removalDate` date DEFAULT NULL,
  `removalRequestedBy` varchar(50) DEFAULT NULL,
  `removalReason` text,
  `STDecisionDate` date DEFAULT NULL,
  `fileRecvdDate` date DEFAULT NULL,
  `sellerAssetManager` varchar(100) DEFAULT NULL,
  `product_type` enum('','Commercial','Notes','Residential','Land','Short Sale','REO','Builder','Bulk Builder','Bulk REO','Bulk Land','Traditional Residential','Trustee','Luxury','C2C','QCD','Quick REO','C2C Asset','Redemption','Post Foreclosure','Rentals','Private Seller - Institutional','MTL','Day 1 REO','Pre Marketing','FCL Marketing') DEFAULT NULL,
  `locked_property` enum('0','1') NOT NULL DEFAULT '0',
  `bulksell` enum('Yes','No') NOT NULL DEFAULT 'No',
  `servicerName` varchar(255) DEFAULT NULL COMMENT 'for servicer in Dump',
  `servicerContact` varchar(100) DEFAULT NULL,
  `servicerPhone` varchar(50) DEFAULT NULL,
  `servicerEmail` varchar(100) DEFAULT NULL,
  `bank` varchar(255) DEFAULT NULL,
  `homeowner_name` varchar(255) DEFAULT NULL,
  `homeowner_phone` varchar(255) DEFAULT NULL,
  `homeowner_email` varchar(255) DEFAULT NULL,
  `insertDate` datetime DEFAULT NULL,
  `realAlertFlag` enum('0','1') DEFAULT '0',
  `ClosingCompanyID2` bigint(20) NOT NULL,
  `downlinerClosingCompanyID2` bigint(20) NOT NULL,
  `InternalNotes` text,
  `presaleStartModifier` smallint(6) DEFAULT NULL,
  `featured` enum('Yes','No') DEFAULT NULL,
  `ReducedCommissionAllowed` enum('Yes','No') DEFAULT NULL,
  `OnlineOnlyCommissionStructure` enum('Yes','No') NOT NULL DEFAULT 'No',
  `bid_increment` int(11) NOT NULL,
  `marketingDescription` varchar(250) DEFAULT NULL,
  `specialProvisionIncentive` float DEFAULT NULL,
  `accept` enum('r','s') DEFAULT NULL,
  `sellerClosingCompany` varchar(200) DEFAULT NULL,
  `sellerClosingCompanyContact` varchar(100) DEFAULT NULL,
  `sellerClosingCompanyEmail` varchar(100) DEFAULT NULL,
  `sellerClosingCompanyPhone` varchar(30) DEFAULT NULL,
  `ServicerLoanNo` varchar(50) DEFAULT NULL,
  `virtual_tour_link` varchar(200) DEFAULT NULL,
  `digital_brochure` varchar(200) DEFAULT NULL,
  `platinum` enum('Yes','No') DEFAULT NULL,
  `preAuction` enum('Yes','No') DEFAULT NULL,
  `seller_CLP` decimal(15,2) DEFAULT NULL COMMENT 'NULL or Numeric',
  `sellerCurrentListDate` date DEFAULT NULL,
  `sellerAlternateId` varchar(100) DEFAULT NULL,
  `sellerAlternateLoanNo` varchar(50) DEFAULT NULL,
  `sellerAddress1` varchar(150) DEFAULT NULL,
  `sellerAddress2` varchar(150) DEFAULT NULL,
  `sellerAddress3` varchar(150) DEFAULT NULL,
  `rcpUploadDate` date DEFAULT NULL,
  `BOVDate` date DEFAULT NULL,
  `assetLevel_deposit` float(8,2) DEFAULT NULL,
  `ContractClosingCompany` varchar(255) DEFAULT NULL,
  `WireInstructionCompany` varchar(255) DEFAULT NULL,
  `googleflag` enum('0','1') NOT NULL DEFAULT '0',
  `saleTime` time DEFAULT NULL,
  `notes` varchar(1000) DEFAULT NULL,
  `notesDate` datetime DEFAULT NULL,
  `notesUpdatedBy` int(100) DEFAULT NULL,
  `MiRequirement` enum('Yes','No','') DEFAULT NULL,
  `MiCompany` varchar(255) DEFAULT NULL,
  `IS_BLUEBOOK_ON` enum('Yes','No') DEFAULT NULL,
  `BLUEBOOK_HIT` smallint(6) NOT NULL,
  `searchID` varchar(20) DEFAULT NULL,
  `otaOff` enum('0','1') NOT NULL DEFAULT '0',
  `otaStatChanged` enum('0','1') NOT NULL DEFAULT '0',
  `postponed_status` enum('0','1','-1','2') NOT NULL DEFAULT '0',
  `property_feature1` text,
  `property_feature2` text,
  `property_feature3` text,
  `property_feature4` text,
  `property_feature5` text,
  `property_feature6` text,
  `property_feature7` text,
  `property_feature8` text,
  `property_feature9` text,
  `property_feature10` text,
  `broker_commission` varchar(128) DEFAULT NULL,
  `community` text,
  `luxHomeImgName` varchar(150) NOT NULL,
  `brokerDesc` text,
  `brokerPhoto` text,
  `Original_Id` varchar(255) DEFAULT NULL,
  `available` varchar(255) DEFAULT NULL,
  `Rollover` varchar(255) NOT NULL,
  `MAIN_EVENT_ID` varchar(255) DEFAULT NULL,
  `MAIN_EVENT_DATE` date DEFAULT NULL,
  `1ST_EVENT` varchar(255) DEFAULT NULL,
  `1ST_EVENT_RO_DATE` date DEFAULT NULL,
  `2ND_EVENT` varchar(255) DEFAULT NULL,
  `2ND_EVENT_RO_DATE` date DEFAULT NULL,
  `3RD_EVENT` varchar(255) DEFAULT NULL,
  `3RD_EVENT_RO_DATE` date DEFAULT NULL,
  `4TH_EVENT` varchar(255) DEFAULT NULL,
  `4TH_EVENT_RO_DATE` date DEFAULT NULL,
  `5TH_EVENT` varchar(255) DEFAULT NULL,
  `5TH_EVENT_RO_DATE` date DEFAULT NULL,
  `ZILLOW_VALUE` varchar(255) DEFAULT NULL,
  `BPO_PVT_VALUE` varchar(255) DEFAULT NULL,
  `AQS_value` int(11) DEFAULT NULL,
  `OH_total_groups` int(11) DEFAULT NULL,
  `total_owed` decimal(20,2) DEFAULT NULL,
  `marketing_spent` decimal(20,2) DEFAULT NULL,
  `RedemptionPeriod` date DEFAULT NULL,
  `EscrowFee` float(9,2) DEFAULT NULL,
  `FinalSellerReserve` int(11) DEFAULT NULL,
  `InitialReserve` int(11) DEFAULT NULL,
  `current_rent` decimal(20,2) DEFAULT NULL,
  `market_rent` decimal(20,2) DEFAULT NULL,
  `lease_expiration_date` varchar(12) DEFAULT NULL,
  `ownership` varchar(100) DEFAULT NULL,
  `security_deposit_charged` decimal(20,2) DEFAULT NULL,
  `security_deposit_received` decimal(20,2) DEFAULT NULL,
  `security_deposit_short` decimal(20,2) DEFAULT NULL,
  `auctionDaySequence` int(11) DEFAULT NULL,
  `bidEnddtUpdateFlag` tinyint(4) NOT NULL,
  `updatedBy` int(11) DEFAULT '0',
  `createdDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` int(11) DEFAULT '0',
  `Homeowner2_name` varchar(100) DEFAULT NULL,
  `Homeowner3_name` varchar(100) DEFAULT NULL,
  `TitleInsuranceCompany` varchar(150) DEFAULT NULL,
  `IncomeProducingProperties` smallint(3) DEFAULT NULL,
  `last_altered_image` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `SFID_Opportunity` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`propertyId`),
  KEY `venueId` (`venueId`),
  KEY `auctiondaystatus` (`auctionDayStatus`),
  KEY `reconcile` (`reconciled`),
  KEY `sellerconfirmation` (`sellerConfirmation`),
  KEY `onlinBidder` (`isOnlineBidder`),
  KEY `propertyCounty` (`propertyCounty`),
  KEY `propertyCity` (`propertyCity`),
  KEY `globalPropId` (`globalPropID`),
  KEY `yearBuilt` (`yearBuilt`),
  KEY `homeSquareFootage` (`homeSquareFootage`),
  KEY `previouslyValuedTo` (`previouslyValuedTo`),
  KEY `propertyAddress` (`propertyAddress`(5)),
  KEY `poolNumber` (`poolNumber`(3)),
  KEY `propertyZip` (`propertyZip`),
  KEY `propertyType` (`propertyType`(5)),
  KEY `biddingStatus` (`biddingStatus`),
  KEY `flag_onlinebid` (`flag_online_bid`),
  KEY `searchID` (`searchID`),
  KEY `loanNo` (`loanNo`),
  KEY `lotPkg` (`lotPackage`),
  KEY `idx_product_type` (`product_type`),
  KEY `property_idx_multi2` (`StatusCSV`,`bidStartDT`,`bidEndDT`,`biddingStatus`,`flag_online_bid`,`autosellerbidover`),
  KEY `property_idx_multi1` (`auctionID`,`StatusCSV`,`bidEndDT`,`bidStartDT`),
  KEY `property_Idx_last_altered` (`last_altered`),
  KEY `property_idx_multi3` (`auctionID`,`globalPropID`)
) ENGINE=InnoDB ;
